name: diffbot
version: 0.1.0
author: Claudio d'Angelis <claudiodangelis@gmail.com>
description: A Dart client library for Diffbot APIs.
homepage: https://github.com/claudiodangelis/diffbot
documentation: http://claudiodangelis.com/docs/diffbot
dependencies:
  js: '>=0.0.25 <0.0.26'
dev_dependencies:
  unittest: any
